apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: spring-petclinic
  namespace: argocd
spec:
  description: Spring PetClinic GitOps project
  sourceRepos:
    - https://github.com/mofayad96/spring-petclinic-Ci-CD.git
  destinations:
    - namespace: petclinic
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: Namespace
  namespaceResourceWhitelist:
    - group: '*'
      kind: ConfigMap
    - group: '*'
      kind: Deployment
    - group: '*'
      kind: Ingress
    - group: '*'
      kind: Secret
    - group: '*'
      kind: Service
