services:
  
  myapp:
    image: themoosalah/spring-app:10.0
    build:
      context: .
      dockerfile: Dockerfile.multi
    container_name: spring-petclinic-app
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/petclinic
      SPRING_DATASOURCE_USERNAME: petclinic
      SPRING_DATASOURCE_PASSWORD: petclinic
      # SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/petclinic
      # SPRING_DATASOURCE_USERNAME: petclinic
      # SPRING_DATASOURCE_PASSWORD: petclinic
    ports:
      - "8080:8080"
    depends_on:
      # - postgres
      - mysql
    networks:
      - petclinic-network

  #========================================================
  mysql:
    image: mysql:9.2
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: petclinic
      MYSQL_PASSWORD: petclinic
      MYSQL_DATABASE: petclinic
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3306:3306"
    networks:
      - petclinic-network
    volumes:
      - petclinic-vol:/var/lib/mysql


  #============================================================
  postgres:
    image: postgres:17.5
    container_name: postgres-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=petclinic
      - POSTGRES_USER=petclinic
      - POSTGRES_DB=petclinic
    networks:
      - petclinic-network
    volumes:
      - petclinic-vol-postgres:/var/lib/postgresql/data
    command: >
      postgres 
      -c listen_addresses='*'
    


  promethues:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - services 

  grafana :
    image: grafana/grafana
    ports:
      - "3000:3000"
    networks:
      - prom-graf
  
volumes:
  petclinic-vol:
  petclinic-vol-postgres:
networks:
  petclinic-network:
    driver: bridge
  prom-graf:
    driver: bridge
