services:
  
  myapp:
    image: 184574354202.dkr.ecr.eu-central-1.amazonaws.com/springpetclinic
    build:
      context: .
      dockerfile: Dockerfile.multistage
    container_name: spring-petclinic-app
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/petclinic
      SPRING_DATASOURCE_USERNAME: petclinic
      SPRING_DATASOURCE_PASSWORD: petclinic
      
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    networks:
      - petclinic-network

  #========================================================
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: petclinic
      MYSQL_PASSWORD: petclinic
      MYSQL_DATABASE: petclinic
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3306:3306"
    networks:
      - petclinic-network
    volumes:
      - petclinic-vol:/var/lib/mysql


  #===========================================================

  
volumes:
  petclinic-vol:
networks:
  petclinic-network:
    driver: bridge
  