FROM  maven:3.9-eclipse-temurin-17-alpine as build

WORKDIR /app

COPY pom.xml .

RUN mvn dependency:go-offline -B

COPY src ./src

RUN mvn package -DskipTests


FROM  eclipse-temurin:17-jre-jammy

RUN groupadd -r -g 1001 petclinic && useradd -r -u 1001 -g petclinic petclinic

WORKDIR /app

COPY --from=build --chown=petclinic:petclinic /app/target/*.jar app.jar

USER petclinic

EXPOSE 8080

CMD [ "java","-jar","app.jar" ]
