# Dev environment overrides
# CI automatically updates image.tag here on every push to main

replicaCount: 1

image:
  tag: "3b5ed05a0e940ea2c75407a820cae425c67fc540"

# Dev uses fewer resources
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 256Mi

mysqlResources:
  limits:
    cpu: 250m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 256Mi

# No autoscaling in dev
autoscaling:
  enabled: false

ingress:
  hosts:
    - host: dev.petclinic.local
      path: /
      pathType: Prefix
