# Dev environment overrides
# CI automatically updates image.tag here on every push to main

replicaCount: 1

image:
  tag: "8a5d19bd13dc639dbb259ddacf1f7cfb4b34d813"

# Dev uses fewer resources
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 256Mi

mysqlResources:
  limits:
    cpu: 250m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 256Mi

# No autoscaling in dev
autoscaling:
  enabled: false

ingress:
  hosts:
    - host: dev.petclinic.local
      path: /
      pathType: Prefix
