apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  mysql-root-pass: cm9vdA==           
  mysql-user: cGV0Y2xpbmlj            
  mysql-password: cGV0Y2xpbmlj          
  mysql-db: cGV0Y2xpbmlj              
